spring:
    datasource:
            url: "jdbc:mysql://localhost:3306/Shop_Management?createDatabaseIfNotExist=true"
            username: root
            password: sapassword
            driverClassName: "com.mysql.cj.jdbc.Driver"
    jpa:
        hibernate.ddl-auto: update
        show-sql: false
server:
    port: 8080
    servlet:
        context-path: /api
jwt:
    signerKey: "AU9hoTlqMf8kZiQFMad+qGhyEvW2ixGuMSx8BR9lE++kORpbf/FlPbSDhfSXTsFW"